### ISSUE TITLE
Move interface

### ISSUE THREAD

**Issue by ghost** [theKGS/MCTS#1]
Just wondering in what situations would you implement these methods and where in the MCTS would these methods be called, since in the simple example it is not used. (I am assuming that even for more complex games outside of board games, this wouldn't be needed?)

**Comment by theKGS** [comment]
You are correct in that these are not used anywhere. It was part of my plan to implement support for nondeterministic games, but I ended up having to focus on my studies. These methods did stay with the interface even though I should have removed them.

**Comment by theKGS** [comment]
I've pushed an update with the two methods removed. More cleanup will be done next week.
